services:
  dbt-postgres-compose:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "15432:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data 
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    networks:
      - postgres-compose-network

  dbt-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "16543:80"
    depends_on:
      - dbt-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge